# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'TestProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SDWebImage'
  pod 'AFNetworking','~>3.0'
  pod 'BaseModel'
  pod 'HMSegmentedControl','~> 1.5'
  pod 'GoogleAnalytics'
  pod 'GoogleMaps'
  pod 'FLAnimatedImage','~>1.0'
  pod 'GoogleIDFASupport'
  pod 'YoutubePlayer-in-WKWebView','~>0.3.0'
  pod 'Branch'
  pod 'AppsFlyerFramework'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'BFRImageViewer','<= 1.2.9'
  pod 'REIOSSDK_54b865b8_5123_461a_accf_d12ed01ce383', '<= 1.0.28’
  #pod 'REIOSSDK_5f7a2e8e_1bdb_4739_9d28_278a2759394c', '<= 1.0.30'


end
